### ISSUE TITLE
Request: please make an example with multiple bezier points

### ISSUE THREAD

**Issue by thednp** [gre/bezier-easing#15]
I remember your code can do multiple point bezier curves. If that's true, please make some example:
* elastic in, out, inOut
* bounce in, out, inOut

:)

**Comment by gre** [comment]
bezier-easing supports only cubic-bezier easings like in CSS Transitions.

Basically here: http://easings.net/

We can do all easings that are mentioned as "JS+CSS"

On that same website you can pick a given one and you can see it's cubic-bezier parameters.
For instance `cubic-bezier(0.175, 0.885, 0.32, 1.275)` for easeOutBack

**Comment by thednp** [comment]
Ok man thanks :)
