### ISSUE TITLE
Breaks if charset is Western (Windows-1252)

### ISSUE THREAD

**Issue by nuthinking** [gre/bezier-easing#16]
![screen shot 2015-07-07 at 14 51 27](https://cloud.githubusercontent.com/assets/163635/8547559/adcf678a-24b7-11e5-96dc-5400958483e2.png)

Had to specify UTF-8 in the meta:

    <meta charset="UTF-8">

**Comment by gre** [comment]
Weird character.

BTW this is not the latest version of BezierEasing right? version 1.0.0 was released some days ago, the API changed a bit too

**Comment by nuthinking** [comment]
Shame the new version can't quickly replace the old one when using it with GASP.
