### ISSUE TITLE
Version 1.0 breaks with angular/bower

### ISSUE THREAD

**Issue by afast** [gre/bezier-easing#18]
Hey...

We were using your version from April 14th. And the new 1.0.0 is broken when we try to load it via bower in an angular app.

When reaching the module.exports sentence at the end it says that module is undefined.

**Comment by gre** [comment]
I've removed the feature that bezier-easing is standalone library and made index.js only supported in CommonJS convention as it seems to be the future (ES6 module syntax, etc..)

Still, I am going to make a build version out of the index.js and also update the bower.json, stay tuned.

**Comment by gre** [comment]
done.
