### ISSUE TITLE
`var global = this;` causes break while working with es6 `import`

### ISSUE THREAD

**Issue by idiotWu** [gre/bezier-easing#19]
I am using this package through bower like this:

```javascript
import BezierEasing from '../bower_components/bezier-easing/bezier-easing';
```

And it broken because [in browsers it's no longer possible to reference the window object through `this` inside a strict mode function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Securing_JavaScript):

![screenshot](https://cloud.githubusercontent.com/assets/6022672/9106866/d983e7ba-3c55-11e5-85f4-b66261463ebd.png)

**Comment by gre** [comment]
thanks
