### ISSUE TITLE
New version, problem with GSAP

### ISSUE THREAD

**Issue by Liqueflies** [gre/bezier-easing#20]
Hello,
I have a minified of a 2014's version of BezierEasing.
When I require with browserify into a var called BezierEasing it works, cause it's a function that return something.

Now I have installed the newest version of BezierEasing with NPM and required index.js into the same var, and GSAP give me an error, cause BezierEasing(myEase) passed into Ease object is not a function.

My Code

```javascript
var BezierEasing = require('bezier-easing');

TweenMax.fromTo($myEl, .7, {
    yPercent: 40,
    autoAlpha:0
}, {
    yPercent: 0,
    autoAlpha:1,
    ease:new Ease(BezierEasing(0.51,0.01,0,1))
});
```
Can I have more info about that ?

Unfortunately I don't have the version number cause I found the min file on my PC from an old project.

Thank You,

Lorenzo

**Comment by gre** [comment]
since this version where you can call `BezierEasing(0.51,0.01,0,1)` there was some breaking changes.

BezierEasing is now an object rather than a function, this is explained here: https://github.com/gre/bezier-easing/pull/14

Now luckily, you have a `.get` function that is bound to this object, so you can just change your code to:

```js
    ease:new Ease(BezierEasing(0.51,0.01,0,1).get)
```

**Comment by vennsoh** [comment]
I am trying to use this with GSAP.
It seems that we don't need .get anymore?

`TweenMax.to(callout1, 1, {x: "+=300", ease:new Ease(BezierEasing(0.51,0.01,0,1))});`

seems to work just fine?

I tried to store BezierEasing(0.51,0.01,0,1) into a variable
var easing = BezierEasing(0.51,0.01,0,1);

`TweenMax.to(callout1, 1, {x: "+=300", ease:new Ease(easing)});`

But it doesn't work.

What will be the best way to store the easing values in a variable?

**Comment by gre** [comment]
yes the API changed in the 2.x version. this has boost perf by ~ 10x https://github.com/gre/bezier-easing/commit/31cf03395480a706a0e3ab2a788eb9693108caa0
it's not longer `easing.get(x)` but directly `easing(x)`

So if new Ease() takes a function from x to value, then yes.

**Comment by gre** [comment]
(we basically rolled back the object oriented approach, back to functional style)
