### ISSUE TITLE
index.js:54 Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by vennsoh** [gre/bezier-easing#23]
I kept having this 
index.js:54 Uncaught ReferenceError: module is not defined

On line 54 of index.js.
Any idea why?

```
module.exports = function bezier (mX1, mY1, mX2, mY2) {
  if (!(0 <= mX1 && mX1 <= 1 && 0 <= mX2 && mX2 <= 1)) {
    throw new Error('bezier x values must be in [0, 1] range');
  }

```

**Comment by vennsoh** [comment]
it seems that I need to run npm install and get the bezier-easing.js from "dist" folder.

**Comment by gre** [comment]
`bezier-easing` aims to be used as a NPM module in a project using webpack / browserify.

that said, as you say we also have a standalone build. it is available here:

https://npmcdn.com/bezier-easing@2.0.3/dist/bezier-easing.js

and

https://npmcdn.com/bezier-easing@2.0.3/dist/bezier-easing.min.js

if you want such web standalone build
