### ISSUE TITLE
Breaking compilation whitespace index.js:140

### ISSUE THREAD

**Issue by andreisocaciu** [gre/bezier-easing#27]
`f.toCSS = function () { return css; };`
This line has a non-standard white space right before `return css;` that breaks compilation using webpack.

**Comment by gre** [comment]
who the hell invented non-standard white space!
thanks for the finding, will fix shortly :)

**Comment by gre** [comment]
mmh, actually can you point me to where this code is? I think it's an old version of the library, maybe you should upgrade?

**Comment by andreisocaciu** [comment]
I have the latest version installed (v2.0.3)
Here's a screenshot of the problem code:
![image](https://cloud.githubusercontent.com/assets/15923667/22291006/b6e9a9ba-e30c-11e6-83bd-da6e4b2b1a2d.png)

**Comment by gre** [comment]
this looks like the v1.x version to me,
this is what v2.0.3 looks like:

```
$ npm i bezier-easing
$ tree node_modules/bezier-easing
node_modules/bezier-easing
├── LICENSE
├── README.md
├── dist
│   ├── bezier-easing.js
│   └── bezier-easing.min.js
├── package.json
└── src
    └── index.js
```


the toCSS function no longer exist in this version. only the bezierEasing function is exposed

**Comment by andreisocaciu** [comment]
You are right. I had v0.4.4 installed. Thanks for your help.
