### ISSUE TITLE
Is this intentional behavior?

### ISSUE THREAD

**Issue by Validark** [gre/bezier-easing#30]
The two `for` loops look like this:
```js
var kSplineTableSize = 11;
var kSampleStepSize = 1.0 / (kSplineTableSize - 1.0);

for (var i = 0; i < kSplineTableSize; ++i) {
	sampleValues[i] = calcBezier(i * kSampleStepSize, mX1, mX2);
}

var intervalStart = 0.0;
var currentSample = 1;
var lastSample = kSplineTableSize - 1;

for (; currentSample !== lastSample && sampleValues[currentSample] <= aX; ++currentSample) {
	intervalStart += kSampleStepSize;
}
--currentSample;

// Interpolate to provide an initial guess for t
var dist = (aX - sampleValues[currentSample]) / (sampleValues[currentSample + 1] - sampleValues[currentSample]);
var guessForT = intervalStart + dist * kSampleStepSize;
```
So as you can see, the first loop creates an array with keys [0, 10]. The second loop runs for keys [1, 9]. This means that `currentSample` cannot be 9 (after `--currentSample`), which also means `intervalStart` can not be 1, even if `sampleValues[10] <= aX`. In other words, `currentSample` is 8 at max and `intervalStart` is 0.9 max. That means that the `dist` estimate will at max will use the values `sampleValues[8]` and `sampleValues[9]`.

I am not sure whether this is intentional or a bug.

If it is intentional, there is no reason to have the first for loop run for `i=10` and should only go to 9, as `sampleValues[10]` is never used by this code.

**Comment by gre** [comment]
```var kSplineTableSize = 11;
var currentSample = 1;
var lastSample = kSplineTableSize - 1;

for (; currentSample !== lastSample; ++currentSample) {
}
--currentSample;

console.log(currentSample)
```

**=> 9**

**Comment by Validark** [comment]
Oh, now that I think about it, that only means that the loop cannot increase intervalStart to 1, and doesn't affect currentSample in that way. My bad.

**Comment by Validark** [comment]
It only runs for [1, 9] but still increases currentSample from 1 to 10 even if it doesn't run on 10

**Comment by gre** [comment]
yes ;) that code might deserve rewriting because is not so readable.

**Comment by Validark** [comment]
Meh, I should have caught that. I for some reason thought that the check statement would keep the iterator from incrementing one last time. I ran a test in C++ real quick on my computer and it ran [1, 9] which seemed to validate my claim, but I didn't print to console what the iterator was right after the for loop because I assumed it would just be the last value. I thought about it in the wrong order.
