### ISSUE TITLE
if I want to get x by y?

### ISSUE THREAD

**Issue by luther-nwpu** [gre/bezier-easing#38]
I need this function。

**Comment by gre** [comment]
There is not a single solution to this problem, bezier curve is not a bijection.

That said, it only happens when one of the handle goes out of [0,1] on the y axis.

So what you can do is simply switch x and y of the bezier parameter and I think you get the reverse function

**Comment by housseynCheriet** [comment]
Best explanation of easing function
https://www.selectionjs.com/animation
